Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 256
      Handler: main.Lambda
      CodeUri: /home/gonczor/Projects/Gradle
      Runtime: java11